// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package codefresh

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "codefresh:index/account:Account":
		r = &Account{}
	case "codefresh:index/context:Context":
		r = &Context{}
	case "codefresh:index/pipeline:Pipeline":
		r = &Pipeline{}
	case "codefresh:index/project:Project":
		r = &Project{}
	case "codefresh:index/registry:Registry":
		r = &Registry{}
	case "codefresh:index/team:Team":
		r = &Team{}
	case "codefresh:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:codefresh" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/account",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/context",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/pipeline",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/registry",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/team",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"codefresh",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"codefresh",
		&pkg{version},
	)
}
