// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package codefresh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Pipeline Resource
//
// The central component of the Codefresh Platform. Pipelines are workflows that contain individual steps. Each step is responsible for a specific action in the process.
// See the [documentation](https://codefresh.io/docs/docs/configure-ci-cd-pipeline/introduction-to-codefresh-pipelines/) for the details.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-codefresh/sdk/go/codefresh"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := codefresh.NewProject(ctx, "testProject", nil)
//			if err != nil {
//				return err
//			}
//			_, err = codefresh.NewPipeline(ctx, "testPipeline", &codefresh.PipelineArgs{
//				Tags: pulumi.StringArray{
//					pulumi.String("production"),
//					pulumi.String("docker"),
//				},
//				Spec: &PipelineSpecArgs{
//					Concurrency:        pulumi.Int(1),
//					BranchConcurrency:  pulumi.Int(1),
//					TriggerConcurrency: pulumi.Int(1),
//					Priority:           pulumi.Int(5),
//					SpecTemplates: PipelineSpecSpecTemplateArray{
//						&PipelineSpecSpecTemplateArgs{
//							Repo:     pulumi.String("codefresh-contrib/react-sample-app"),
//							Path:     pulumi.String("./codefresh.yml"),
//							Revision: pulumi.String("master"),
//							Context:  pulumi.String("git"),
//						},
//					},
//					Contexts: pulumi.StringArray{
//						pulumi.String("context1-name"),
//						pulumi.String("context2-name"),
//					},
//					Triggers: PipelineSpecTriggerArray{
//						&PipelineSpecTriggerArgs{
//							BranchRegex: pulumi.String("/.*/gi"),
//							Context:     pulumi.String("git"),
//							Description: pulumi.String("Trigger for commits"),
//							Disabled:    pulumi.Bool(false),
//							Events: pulumi.StringArray{
//								pulumi.String("push.heads"),
//							},
//							ModifiedFilesGlob: pulumi.String(""),
//							Name:              pulumi.String("commits"),
//							Provider:          pulumi.String("github"),
//							Repo:              pulumi.String("codefresh-contrib/react-sample-app"),
//							Type:              pulumi.String("git"),
//						},
//						&PipelineSpecTriggerArgs{
//							BranchRegex: pulumi.String("/.*/gi"),
//							Context:     pulumi.String("git"),
//							Description: pulumi.String("Trigger for tags"),
//							Disabled:    pulumi.Bool(false),
//							Events: pulumi.StringArray{
//								pulumi.String("push.tags"),
//							},
//							ModifiedFilesGlob: pulumi.String(""),
//							CommitStatusTitle: pulumi.String("tags-trigger"),
//							Name:              pulumi.String("tags"),
//							Provider:          pulumi.String("github"),
//							Repo:              pulumi.String("codefresh-contrib/react-sample-app"),
//							Type:              pulumi.String("git"),
//						},
//					},
//					Variables: pulumi.StringMap{
//						"MY_PIP_VAR":      pulumi.String("value"),
//						"ANOTHER_PIP_VAR": pulumi.String("another_value"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
//
//	$ pulumi import codefresh:index/pipeline:Pipeline test xxxxxxxxxxxxxxxxxxx
//
// ```
type Pipeline struct {
	pulumi.CustomResourceState

	// Boolean that specifies if the build logs are publicly accessible. Default: false
	IsPublic pulumi.BoolPtrOutput `pulumi:"isPublic"`
	// The display name for the pipeline.
	Name pulumi.StringOutput `pulumi:"name"`
	// A string with original yaml pipeline.
	// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
	// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
	OriginalYamlString pulumi.StringPtrOutput `pulumi:"originalYamlString"`
	ProjectId          pulumi.StringOutput    `pulumi:"projectId"`
	// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
	Revision pulumi.IntOutput `pulumi:"revision"`
	// A collection of `spec` blocks as documented below.
	Spec PipelineSpecPtrOutput `pulumi:"spec"`
	// A list of tags to mark a project for easy management and access control.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
}

// NewPipeline registers a new resource with the given unique name, arguments, and options.
func NewPipeline(ctx *pulumi.Context,
	name string, args *PipelineArgs, opts ...pulumi.ResourceOption) (*Pipeline, error) {
	if args == nil {
		args = &PipelineArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource Pipeline
	err := ctx.RegisterResource("codefresh:index/pipeline:Pipeline", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPipeline gets an existing Pipeline resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPipeline(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PipelineState, opts ...pulumi.ResourceOption) (*Pipeline, error) {
	var resource Pipeline
	err := ctx.ReadResource("codefresh:index/pipeline:Pipeline", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Pipeline resources.
type pipelineState struct {
	// Boolean that specifies if the build logs are publicly accessible. Default: false
	IsPublic *bool `pulumi:"isPublic"`
	// The display name for the pipeline.
	Name *string `pulumi:"name"`
	// A string with original yaml pipeline.
	// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
	// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
	OriginalYamlString *string `pulumi:"originalYamlString"`
	ProjectId          *string `pulumi:"projectId"`
	// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
	Revision *int `pulumi:"revision"`
	// A collection of `spec` blocks as documented below.
	Spec *PipelineSpec `pulumi:"spec"`
	// A list of tags to mark a project for easy management and access control.
	Tags []string `pulumi:"tags"`
}

type PipelineState struct {
	// Boolean that specifies if the build logs are publicly accessible. Default: false
	IsPublic pulumi.BoolPtrInput
	// The display name for the pipeline.
	Name pulumi.StringPtrInput
	// A string with original yaml pipeline.
	// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
	// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
	OriginalYamlString pulumi.StringPtrInput
	ProjectId          pulumi.StringPtrInput
	// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
	Revision pulumi.IntPtrInput
	// A collection of `spec` blocks as documented below.
	Spec PipelineSpecPtrInput
	// A list of tags to mark a project for easy management and access control.
	Tags pulumi.StringArrayInput
}

func (PipelineState) ElementType() reflect.Type {
	return reflect.TypeOf((*pipelineState)(nil)).Elem()
}

type pipelineArgs struct {
	// Boolean that specifies if the build logs are publicly accessible. Default: false
	IsPublic *bool `pulumi:"isPublic"`
	// The display name for the pipeline.
	Name *string `pulumi:"name"`
	// A string with original yaml pipeline.
	// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
	// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
	OriginalYamlString *string `pulumi:"originalYamlString"`
	// A collection of `spec` blocks as documented below.
	Spec *PipelineSpec `pulumi:"spec"`
	// A list of tags to mark a project for easy management and access control.
	Tags []string `pulumi:"tags"`
}

// The set of arguments for constructing a Pipeline resource.
type PipelineArgs struct {
	// Boolean that specifies if the build logs are publicly accessible. Default: false
	IsPublic pulumi.BoolPtrInput
	// The display name for the pipeline.
	Name pulumi.StringPtrInput
	// A string with original yaml pipeline.
	// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
	// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
	OriginalYamlString pulumi.StringPtrInput
	// A collection of `spec` blocks as documented below.
	Spec PipelineSpecPtrInput
	// A list of tags to mark a project for easy management and access control.
	Tags pulumi.StringArrayInput
}

func (PipelineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pipelineArgs)(nil)).Elem()
}

type PipelineInput interface {
	pulumi.Input

	ToPipelineOutput() PipelineOutput
	ToPipelineOutputWithContext(ctx context.Context) PipelineOutput
}

func (*Pipeline) ElementType() reflect.Type {
	return reflect.TypeOf((**Pipeline)(nil)).Elem()
}

func (i *Pipeline) ToPipelineOutput() PipelineOutput {
	return i.ToPipelineOutputWithContext(context.Background())
}

func (i *Pipeline) ToPipelineOutputWithContext(ctx context.Context) PipelineOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PipelineOutput)
}

// PipelineArrayInput is an input type that accepts PipelineArray and PipelineArrayOutput values.
// You can construct a concrete instance of `PipelineArrayInput` via:
//
//	PipelineArray{ PipelineArgs{...} }
type PipelineArrayInput interface {
	pulumi.Input

	ToPipelineArrayOutput() PipelineArrayOutput
	ToPipelineArrayOutputWithContext(context.Context) PipelineArrayOutput
}

type PipelineArray []PipelineInput

func (PipelineArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Pipeline)(nil)).Elem()
}

func (i PipelineArray) ToPipelineArrayOutput() PipelineArrayOutput {
	return i.ToPipelineArrayOutputWithContext(context.Background())
}

func (i PipelineArray) ToPipelineArrayOutputWithContext(ctx context.Context) PipelineArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PipelineArrayOutput)
}

// PipelineMapInput is an input type that accepts PipelineMap and PipelineMapOutput values.
// You can construct a concrete instance of `PipelineMapInput` via:
//
//	PipelineMap{ "key": PipelineArgs{...} }
type PipelineMapInput interface {
	pulumi.Input

	ToPipelineMapOutput() PipelineMapOutput
	ToPipelineMapOutputWithContext(context.Context) PipelineMapOutput
}

type PipelineMap map[string]PipelineInput

func (PipelineMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Pipeline)(nil)).Elem()
}

func (i PipelineMap) ToPipelineMapOutput() PipelineMapOutput {
	return i.ToPipelineMapOutputWithContext(context.Background())
}

func (i PipelineMap) ToPipelineMapOutputWithContext(ctx context.Context) PipelineMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PipelineMapOutput)
}

type PipelineOutput struct{ *pulumi.OutputState }

func (PipelineOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Pipeline)(nil)).Elem()
}

func (o PipelineOutput) ToPipelineOutput() PipelineOutput {
	return o
}

func (o PipelineOutput) ToPipelineOutputWithContext(ctx context.Context) PipelineOutput {
	return o
}

// Boolean that specifies if the build logs are publicly accessible. Default: false
func (o PipelineOutput) IsPublic() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.BoolPtrOutput { return v.IsPublic }).(pulumi.BoolPtrOutput)
}

// The display name for the pipeline.
func (o PipelineOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A string with original yaml pipeline.
// - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
// - or `originalYamlString = file("/path/to/my/codefresh.yml")`
func (o PipelineOutput) OriginalYamlString() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.StringPtrOutput { return v.OriginalYamlString }).(pulumi.StringPtrOutput)
}

func (o PipelineOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
func (o PipelineOutput) Revision() pulumi.IntOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.IntOutput { return v.Revision }).(pulumi.IntOutput)
}

// A collection of `spec` blocks as documented below.
func (o PipelineOutput) Spec() PipelineSpecPtrOutput {
	return o.ApplyT(func(v *Pipeline) PipelineSpecPtrOutput { return v.Spec }).(PipelineSpecPtrOutput)
}

// A list of tags to mark a project for easy management and access control.
func (o PipelineOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Pipeline) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

type PipelineArrayOutput struct{ *pulumi.OutputState }

func (PipelineArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Pipeline)(nil)).Elem()
}

func (o PipelineArrayOutput) ToPipelineArrayOutput() PipelineArrayOutput {
	return o
}

func (o PipelineArrayOutput) ToPipelineArrayOutputWithContext(ctx context.Context) PipelineArrayOutput {
	return o
}

func (o PipelineArrayOutput) Index(i pulumi.IntInput) PipelineOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Pipeline {
		return vs[0].([]*Pipeline)[vs[1].(int)]
	}).(PipelineOutput)
}

type PipelineMapOutput struct{ *pulumi.OutputState }

func (PipelineMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Pipeline)(nil)).Elem()
}

func (o PipelineMapOutput) ToPipelineMapOutput() PipelineMapOutput {
	return o
}

func (o PipelineMapOutput) ToPipelineMapOutputWithContext(ctx context.Context) PipelineMapOutput {
	return o
}

func (o PipelineMapOutput) MapIndex(k pulumi.StringInput) PipelineOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Pipeline {
		return vs[0].(map[string]*Pipeline)[vs[1].(string)]
	}).(PipelineOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PipelineInput)(nil)).Elem(), &Pipeline{})
	pulumi.RegisterInputType(reflect.TypeOf((*PipelineArrayInput)(nil)).Elem(), PipelineArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PipelineMapInput)(nil)).Elem(), PipelineMap{})
	pulumi.RegisterOutputType(PipelineOutput{})
	pulumi.RegisterOutputType(PipelineArrayOutput{})
	pulumi.RegisterOutputType(PipelineMapOutput{})
}
