// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package codefresh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## # Team resource
//
// Team is used as a part of access control and allow to define what teams have access to which clusters and pipelines.
// See the [documentation](https://codefresh.io/docs/docs/administration/access-control/).
//
// ## Example usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-codefresh/sdk/go/codefresh"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := codefresh.NewTeam(ctx, "developers", &codefresh.TeamArgs{
//				Users: pulumi.StringArray{
//					pulumi.String("5efc3cb6355c6647041b6e49"),
//					pulumi.String("59009221c102763beda7cf04"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type Team struct {
	pulumi.CustomResourceState

	// The relevant Account ID.
	AccountId pulumi.StringOutput `pulumi:"accountId"`
	// The display name for the team.
	Name pulumi.StringOutput `pulumi:"name"`
	// A list of tags to mark a team for easy management.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// The type of the team. Possible values:
	// - __default__
	// - __admin__
	Type pulumi.StringPtrOutput `pulumi:"type"`
	// A list of user IDs that should be in the team.
	Users pulumi.StringArrayOutput `pulumi:"users"`
}

// NewTeam registers a new resource with the given unique name, arguments, and options.
func NewTeam(ctx *pulumi.Context,
	name string, args *TeamArgs, opts ...pulumi.ResourceOption) (*Team, error) {
	if args == nil {
		args = &TeamArgs{}
	}

	opts = pkgResourceDefaultOpts(opts)
	var resource Team
	err := ctx.RegisterResource("codefresh:index/team:Team", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTeam gets an existing Team resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTeam(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TeamState, opts ...pulumi.ResourceOption) (*Team, error) {
	var resource Team
	err := ctx.ReadResource("codefresh:index/team:Team", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Team resources.
type teamState struct {
	// The relevant Account ID.
	AccountId *string `pulumi:"accountId"`
	// The display name for the team.
	Name *string `pulumi:"name"`
	// A list of tags to mark a team for easy management.
	Tags []string `pulumi:"tags"`
	// The type of the team. Possible values:
	// - __default__
	// - __admin__
	Type *string `pulumi:"type"`
	// A list of user IDs that should be in the team.
	Users []string `pulumi:"users"`
}

type TeamState struct {
	// The relevant Account ID.
	AccountId pulumi.StringPtrInput
	// The display name for the team.
	Name pulumi.StringPtrInput
	// A list of tags to mark a team for easy management.
	Tags pulumi.StringArrayInput
	// The type of the team. Possible values:
	// - __default__
	// - __admin__
	Type pulumi.StringPtrInput
	// A list of user IDs that should be in the team.
	Users pulumi.StringArrayInput
}

func (TeamState) ElementType() reflect.Type {
	return reflect.TypeOf((*teamState)(nil)).Elem()
}

type teamArgs struct {
	// The relevant Account ID.
	AccountId *string `pulumi:"accountId"`
	// The display name for the team.
	Name *string `pulumi:"name"`
	// A list of tags to mark a team for easy management.
	Tags []string `pulumi:"tags"`
	// The type of the team. Possible values:
	// - __default__
	// - __admin__
	Type *string `pulumi:"type"`
	// A list of user IDs that should be in the team.
	Users []string `pulumi:"users"`
}

// The set of arguments for constructing a Team resource.
type TeamArgs struct {
	// The relevant Account ID.
	AccountId pulumi.StringPtrInput
	// The display name for the team.
	Name pulumi.StringPtrInput
	// A list of tags to mark a team for easy management.
	Tags pulumi.StringArrayInput
	// The type of the team. Possible values:
	// - __default__
	// - __admin__
	Type pulumi.StringPtrInput
	// A list of user IDs that should be in the team.
	Users pulumi.StringArrayInput
}

func (TeamArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*teamArgs)(nil)).Elem()
}

type TeamInput interface {
	pulumi.Input

	ToTeamOutput() TeamOutput
	ToTeamOutputWithContext(ctx context.Context) TeamOutput
}

func (*Team) ElementType() reflect.Type {
	return reflect.TypeOf((**Team)(nil)).Elem()
}

func (i *Team) ToTeamOutput() TeamOutput {
	return i.ToTeamOutputWithContext(context.Background())
}

func (i *Team) ToTeamOutputWithContext(ctx context.Context) TeamOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TeamOutput)
}

// TeamArrayInput is an input type that accepts TeamArray and TeamArrayOutput values.
// You can construct a concrete instance of `TeamArrayInput` via:
//
//	TeamArray{ TeamArgs{...} }
type TeamArrayInput interface {
	pulumi.Input

	ToTeamArrayOutput() TeamArrayOutput
	ToTeamArrayOutputWithContext(context.Context) TeamArrayOutput
}

type TeamArray []TeamInput

func (TeamArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Team)(nil)).Elem()
}

func (i TeamArray) ToTeamArrayOutput() TeamArrayOutput {
	return i.ToTeamArrayOutputWithContext(context.Background())
}

func (i TeamArray) ToTeamArrayOutputWithContext(ctx context.Context) TeamArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TeamArrayOutput)
}

// TeamMapInput is an input type that accepts TeamMap and TeamMapOutput values.
// You can construct a concrete instance of `TeamMapInput` via:
//
//	TeamMap{ "key": TeamArgs{...} }
type TeamMapInput interface {
	pulumi.Input

	ToTeamMapOutput() TeamMapOutput
	ToTeamMapOutputWithContext(context.Context) TeamMapOutput
}

type TeamMap map[string]TeamInput

func (TeamMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Team)(nil)).Elem()
}

func (i TeamMap) ToTeamMapOutput() TeamMapOutput {
	return i.ToTeamMapOutputWithContext(context.Background())
}

func (i TeamMap) ToTeamMapOutputWithContext(ctx context.Context) TeamMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TeamMapOutput)
}

type TeamOutput struct{ *pulumi.OutputState }

func (TeamOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Team)(nil)).Elem()
}

func (o TeamOutput) ToTeamOutput() TeamOutput {
	return o
}

func (o TeamOutput) ToTeamOutputWithContext(ctx context.Context) TeamOutput {
	return o
}

// The relevant Account ID.
func (o TeamOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Team) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

// The display name for the team.
func (o TeamOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Team) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A list of tags to mark a team for easy management.
func (o TeamOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Team) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// The type of the team. Possible values:
// - __default__
// - __admin__
func (o TeamOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Team) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

// A list of user IDs that should be in the team.
func (o TeamOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Team) pulumi.StringArrayOutput { return v.Users }).(pulumi.StringArrayOutput)
}

type TeamArrayOutput struct{ *pulumi.OutputState }

func (TeamArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Team)(nil)).Elem()
}

func (o TeamArrayOutput) ToTeamArrayOutput() TeamArrayOutput {
	return o
}

func (o TeamArrayOutput) ToTeamArrayOutputWithContext(ctx context.Context) TeamArrayOutput {
	return o
}

func (o TeamArrayOutput) Index(i pulumi.IntInput) TeamOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Team {
		return vs[0].([]*Team)[vs[1].(int)]
	}).(TeamOutput)
}

type TeamMapOutput struct{ *pulumi.OutputState }

func (TeamMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Team)(nil)).Elem()
}

func (o TeamMapOutput) ToTeamMapOutput() TeamMapOutput {
	return o
}

func (o TeamMapOutput) ToTeamMapOutputWithContext(ctx context.Context) TeamMapOutput {
	return o
}

func (o TeamMapOutput) MapIndex(k pulumi.StringInput) TeamOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Team {
		return vs[0].(map[string]*Team)[vs[1].(string)]
	}).(TeamOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TeamInput)(nil)).Elem(), &Team{})
	pulumi.RegisterInputType(reflect.TypeOf((*TeamArrayInput)(nil)).Elem(), TeamArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TeamMapInput)(nil)).Elem(), TeamMap{})
	pulumi.RegisterOutputType(TeamOutput{})
	pulumi.RegisterOutputType(TeamArrayOutput{})
	pulumi.RegisterOutputType(TeamMapOutput{})
}
