// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class AccountLimit
    {
        /// <summary>
        /// Max account's collaborators number.
        /// </summary>
        public readonly int Collaborators;
        /// <summary>
        /// -(Optional) How long in weeks will the builds be stored.
        /// </summary>
        public readonly int? DataRetentionWeeks;

        [OutputConstructor]
        private AccountLimit(
            int collaborators,

            int? dataRetentionWeeks)
        {
            Collaborators = collaborators;
            DataRetentionWeeks = dataRetentionWeeks;
        }
    }
}
