// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class ContextSpec
    {
        /// <summary>
        /// A `config` block as documented below. Shared Config [spec](https://codefresh-io.github.io/cli/contexts/spec/config/).
        /// </summary>
        public readonly Outputs.ContextSpecConfig? Config;
        /// <summary>
        /// A `secret` block as documented below. Shared Secret [spec](https://codefresh-io.github.io/cli/contexts/spec/secret/).
        /// </summary>
        public readonly Outputs.ContextSpecSecret? Secret;
        /// <summary>
        /// A `secretyaml` block as documented below. Secret Yaml Configuration Context[spec](https://codefresh-io.github.io/cli/contexts/spec/secret-yaml/).
        /// </summary>
        public readonly Outputs.ContextSpecSecretyaml? Secretyaml;
        public readonly Outputs.ContextSpecStorageazuref? Storageazuref;
        public readonly Outputs.ContextSpecStoragegc? Storagegc;
        public readonly Outputs.ContextSpecStorages3? Storages3;
        /// <summary>
        /// A `yaml` block as documented below. Yaml Configuration Context [spec](https://codefresh-io.github.io/cli/contexts/spec/yaml/).
        /// </summary>
        public readonly Outputs.ContextSpecYaml? Yaml;

        [OutputConstructor]
        private ContextSpec(
            Outputs.ContextSpecConfig? config,

            Outputs.ContextSpecSecret? secret,

            Outputs.ContextSpecSecretyaml? secretyaml,

            Outputs.ContextSpecStorageazuref? storageazuref,

            Outputs.ContextSpecStoragegc? storagegc,

            Outputs.ContextSpecStorages3? storages3,

            Outputs.ContextSpecYaml? yaml)
        {
            Config = config;
            Secret = secret;
            Secretyaml = secretyaml;
            Storageazuref = storageazuref;
            Storagegc = storagegc;
            Storages3 = storages3;
            Yaml = yaml;
        }
    }
}
