// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class ContextSpecSecretyaml
    {
        /// <summary>
        /// String representing a YAML file content
        /// </summary>
        public readonly string Data;

        [OutputConstructor]
        private ContextSpecSecretyaml(string data)
        {
            Data = data;
        }
    }
}
