// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class PipelineSpecSpecTemplate
    {
        /// <summary>
        /// The Codefresh Git [context](https://codefresh.io/docs/docs/integrations/git-providers/).
        /// </summary>
        public readonly string? Context;
        /// <summary>
        /// Default value - **git**.
        /// </summary>
        public readonly string? Location;
        /// <summary>
        /// The relative path to the Codefresh pipeline file.
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// The GitHub `account/repo_name`.
        /// </summary>
        public readonly string Repo;
        /// <summary>
        /// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
        /// </summary>
        public readonly string Revision;

        [OutputConstructor]
        private PipelineSpecSpecTemplate(
            string? context,

            string? location,

            string path,

            string repo,

            string revision)
        {
            Context = context;
            Location = location;
            Path = path;
            Repo = repo;
            Revision = revision;
        }
    }
}
