// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class PipelineSpecTriggerRuntimeEnvironment
    {
        /// <summary>
        /// A required amount of CPU.
        /// </summary>
        public readonly string? Cpu;
        /// <summary>
        /// A pipeline shared storage.
        /// </summary>
        public readonly string? DindStorage;
        /// <summary>
        /// A required amount of memory.
        /// </summary>
        public readonly string? Memory;
        /// <summary>
        /// A name of runtime.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private PipelineSpecTriggerRuntimeEnvironment(
            string? cpu,

            string? dindStorage,

            string? memory,

            string? name)
        {
            Cpu = cpu;
            DindStorage = dindStorage;
            Memory = memory;
            Name = name;
        }
    }
}
