// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class PipelineSpecTerminationPolicyOnCreateBranch
    {
        /// <summary>
        /// A regular expression to filter the branches on with the termination policy applies.
        /// </summary>
        public readonly string? BranchName;
        /// <summary>
        /// Boolean. See table below for usage.
        /// </summary>
        public readonly bool? IgnoreBranch;
        /// <summary>
        /// Boolean. See table below for usage.
        /// </summary>
        public readonly bool? IgnoreTrigger;

        [OutputConstructor]
        private PipelineSpecTerminationPolicyOnCreateBranch(
            string? branchName,

            bool? ignoreBranch,

            bool? ignoreTrigger)
        {
            BranchName = branchName;
            IgnoreBranch = ignoreBranch;
            IgnoreTrigger = ignoreTrigger;
        }
    }
}
