// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class RegistrySpecGcr
    {
        /// <summary>
        /// _(Required)_ String representing one of the Google's gcr domains
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// _(Required)_ String representing service account json file contents
        /// </summary>
        public readonly string Keyfile;
        /// <summary>
        /// _(Optional)_ String. See the [docs](https://codefresh.io/docs/docs/integrations/docker-registries/#using-an-optional-repository-prefix).
        /// </summary>
        public readonly string? RepositoryPrefix;

        [OutputConstructor]
        private RegistrySpecGcr(
            string domain,

            string keyfile,

            string? repositoryPrefix)
        {
            Domain = domain;
            Keyfile = keyfile;
            RepositoryPrefix = repositoryPrefix;
        }
    }
}
