// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Outputs
{

    [OutputType]
    public sealed class RegistrySpecBintray
    {
        /// <summary>
        /// _(Required)_ String representing the bintray domain
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// _(Optional)_ String. See the [docs](https://codefresh.io/docs/docs/integrations/docker-registries/#using-an-optional-repository-prefix).
        /// </summary>
        public readonly string? RepositoryPrefix;
        /// <summary>
        /// _(Required)_ String representing token
        /// </summary>
        public readonly string Token;
        /// <summary>
        /// _(Required)_ String representing the username
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private RegistrySpecBintray(
            string domain,

            string? repositoryPrefix,

            string token,

            string username)
        {
            Domain = domain;
            RepositoryPrefix = repositoryPrefix;
            Token = token;
            Username = username;
        }
    }
}
