// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetApiUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "codefresh:apiUrl")
}
func GetToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "codefresh:token")
}
