// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class AccountLimitGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Max account's collaborators number.
        /// </summary>
        [Input("collaborators", required: true)]
        public Input<int> Collaborators { get; set; } = null!;

        /// <summary>
        /// -(Optional) How long in weeks will the builds be stored.
        /// </summary>
        [Input("dataRetentionWeeks")]
        public Input<int>? DataRetentionWeeks { get; set; }

        public AccountLimitGetArgs()
        {
        }
        public static new AccountLimitGetArgs Empty => new AccountLimitGetArgs();
    }
}
