// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class ContextSpecStorageazurefDataGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("auth", required: true)]
        public Input<Inputs.ContextSpecStorageazurefDataAuthGetArgs> Auth { get; set; } = null!;

        public ContextSpecStorageazurefDataGetArgs()
        {
        }
        public static new ContextSpecStorageazurefDataGetArgs Empty => new ContextSpecStorageazurefDataGetArgs();
    }
}
