// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class ContextSpecYamlArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// String representing a YAML file content
        /// </summary>
        [Input("data", required: true)]
        public Input<string> Data { get; set; } = null!;

        public ContextSpecYamlArgs()
        {
        }
        public static new ContextSpecYamlArgs Empty => new ContextSpecYamlArgs();
    }
}
