// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class PipelineSpecTerminationPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A `on_create_branch` block as documented below.
        /// </summary>
        [Input("onCreateBranch")]
        public Input<Inputs.PipelineSpecTerminationPolicyOnCreateBranchGetArgs>? OnCreateBranch { get; set; }

        /// <summary>
        /// Boolean. Enables the policy `Once a build is terminated, terminate all child builds initiated from it`. Default false.
        /// </summary>
        [Input("onTerminateAnnotation")]
        public Input<bool>? OnTerminateAnnotation { get; set; }

        public PipelineSpecTerminationPolicyGetArgs()
        {
        }
        public static new PipelineSpecTerminationPolicyGetArgs Empty => new PipelineSpecTerminationPolicyGetArgs();
    }
}
