// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class PipelineSpecSpecTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Codefresh Git [context](https://codefresh.io/docs/docs/integrations/git-providers/).
        /// </summary>
        [Input("context")]
        public Input<string>? Context { get; set; }

        /// <summary>
        /// Default value - **git**.
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The relative path to the Codefresh pipeline file.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// The GitHub `account/repo_name`.
        /// </summary>
        [Input("repo", required: true)]
        public Input<string> Repo { get; set; } = null!;

        /// <summary>
        /// The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
        /// </summary>
        [Input("revision", required: true)]
        public Input<string> Revision { get; set; } = null!;

        public PipelineSpecSpecTemplateArgs()
        {
        }
        public static new PipelineSpecSpecTemplateArgs Empty => new PipelineSpecSpecTemplateArgs();
    }
}
