// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class PipelineSpecTerminationPolicyOnCreateBranchGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A regular expression to filter the branches on with the termination policy applies.
        /// </summary>
        [Input("branchName")]
        public Input<string>? BranchName { get; set; }

        /// <summary>
        /// Boolean. See table below for usage.
        /// </summary>
        [Input("ignoreBranch")]
        public Input<bool>? IgnoreBranch { get; set; }

        /// <summary>
        /// Boolean. See table below for usage.
        /// </summary>
        [Input("ignoreTrigger")]
        public Input<bool>? IgnoreTrigger { get; set; }

        public PipelineSpecTerminationPolicyOnCreateBranchGetArgs()
        {
        }
        public static new PipelineSpecTerminationPolicyOnCreateBranchGetArgs Empty => new PipelineSpecTerminationPolicyOnCreateBranchGetArgs();
    }
}
