// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class RegistrySpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("acr")]
        public Input<Inputs.RegistrySpecAcrArgs>? Acr { get; set; }

        [Input("bintray")]
        public Input<Inputs.RegistrySpecBintrayArgs>? Bintray { get; set; }

        [Input("dockerhub")]
        public Input<Inputs.RegistrySpecDockerhubArgs>? Dockerhub { get; set; }

        [Input("ecr")]
        public Input<Inputs.RegistrySpecEcrArgs>? Ecr { get; set; }

        [Input("gar")]
        public Input<Inputs.RegistrySpecGarArgs>? Gar { get; set; }

        [Input("gcr")]
        public Input<Inputs.RegistrySpecGcrArgs>? Gcr { get; set; }

        [Input("other")]
        public Input<Inputs.RegistrySpecOtherArgs>? Other { get; set; }

        public RegistrySpecArgs()
        {
        }
        public static new RegistrySpecArgs Empty => new RegistrySpecArgs();
    }
}
