// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class RegistrySpecOtherGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// _(Optional, Default = false)_ Bool. See the [docs](https://codefresh.io/docs/docs/administration/behind-the-firewall/#accessing-an-internal-docker-registry).
        /// </summary>
        [Input("behindFirewall")]
        public Input<bool>? BehindFirewall { get; set; }

        /// <summary>
        /// _(Required)_ String representing the bintray domain
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// _(Required)_ String representing token
        /// </summary>
        [Input("password", required: true)]
        public Input<string> Password { get; set; } = null!;

        /// <summary>
        /// _(Optional)_ String. See the [docs](https://codefresh.io/docs/docs/integrations/docker-registries/#using-an-optional-repository-prefix).
        /// </summary>
        [Input("repositoryPrefix")]
        public Input<string>? RepositoryPrefix { get; set; }

        /// <summary>
        /// _(Required)_ String representing the username
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public RegistrySpecOtherGetArgs()
        {
        }
        public static new RegistrySpecOtherGetArgs Empty => new RegistrySpecOtherGetArgs();
    }
}
