// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Codefresh.Inputs
{

    public sealed class RegistrySpecGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("acr")]
        public Input<Inputs.RegistrySpecAcrGetArgs>? Acr { get; set; }

        [Input("bintray")]
        public Input<Inputs.RegistrySpecBintrayGetArgs>? Bintray { get; set; }

        [Input("dockerhub")]
        public Input<Inputs.RegistrySpecDockerhubGetArgs>? Dockerhub { get; set; }

        [Input("ecr")]
        public Input<Inputs.RegistrySpecEcrGetArgs>? Ecr { get; set; }

        [Input("gar")]
        public Input<Inputs.RegistrySpecGarGetArgs>? Gar { get; set; }

        [Input("gcr")]
        public Input<Inputs.RegistrySpecGcrGetArgs>? Gcr { get; set; }

        [Input("other")]
        public Input<Inputs.RegistrySpecOtherGetArgs>? Other { get; set; }

        public RegistrySpecGetArgs()
        {
        }
        public static new RegistrySpecGetArgs Empty => new RegistrySpecGetArgs();
    }
}
