// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./account";
export * from "./context";
export * from "./pipeline";
export * from "./project";
export * from "./provider";
export * from "./registry";
export * from "./team";
export * from "./user";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { Account } from "./account";
import { Context } from "./context";
import { Pipeline } from "./pipeline";
import { Project } from "./project";
import { Registry } from "./registry";
import { Team } from "./team";
import { User } from "./user";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "codefresh:index/account:Account":
                return new Account(name, <any>undefined, { urn })
            case "codefresh:index/context:Context":
                return new Context(name, <any>undefined, { urn })
            case "codefresh:index/pipeline:Pipeline":
                return new Pipeline(name, <any>undefined, { urn })
            case "codefresh:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "codefresh:index/registry:Registry":
                return new Registry(name, <any>undefined, { urn })
            case "codefresh:index/team:Team":
                return new Team(name, <any>undefined, { urn })
            case "codefresh:index/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("codefresh", "index/account", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/context", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/pipeline", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/project", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/registry", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/team", _module)
pulumi.runtime.registerResourceModule("codefresh", "index/user", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("codefresh", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:codefresh") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
