// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * ## # Pipeline Resource
 *
 * The central component of the Codefresh Platform. Pipelines are workflows that contain individual steps. Each step is responsible for a specific action in the process.
 * See the [documentation](https://codefresh.io/docs/docs/configure-ci-cd-pipeline/introduction-to-codefresh-pipelines/) for the details.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as codefresh from "@pulumiverse/codefresh";
 *
 * const testProject = new codefresh.Project("testProject", {});
 * const testPipeline = new codefresh.Pipeline("testPipeline", {
 *     tags: [
 *         "production",
 *         "docker",
 *     ],
 *     spec: {
 *         concurrency: 1,
 *         branchConcurrency: 1,
 *         triggerConcurrency: 1,
 *         priority: 5,
 *         specTemplates: [{
 *             repo: "codefresh-contrib/react-sample-app",
 *             path: "./codefresh.yml",
 *             revision: "master",
 *             context: "git",
 *         }],
 *         contexts: [
 *             "context1-name",
 *             "context2-name",
 *         ],
 *         triggers: [
 *             {
 *                 branchRegex: "/.*&#47;gi",
 *                 context: "git",
 *                 description: "Trigger for commits",
 *                 disabled: false,
 *                 events: ["push.heads"],
 *                 modifiedFilesGlob: "",
 *                 name: "commits",
 *                 provider: "github",
 *                 repo: "codefresh-contrib/react-sample-app",
 *                 type: "git",
 *             },
 *             {
 *                 branchRegex: "/.*&#47;gi",
 *                 context: "git",
 *                 description: "Trigger for tags",
 *                 disabled: false,
 *                 events: ["push.tags"],
 *                 modifiedFilesGlob: "",
 *                 commitStatusTitle: "tags-trigger",
 *                 name: "tags",
 *                 provider: "github",
 *                 repo: "codefresh-contrib/react-sample-app",
 *                 type: "git",
 *             },
 *         ],
 *         variables: {
 *             MY_PIP_VAR: "value",
 *             ANOTHER_PIP_VAR: "another_value",
 *         },
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 *  $ pulumi import codefresh:index/pipeline:Pipeline test xxxxxxxxxxxxxxxxxxx
 * ```
 */
export class Pipeline extends pulumi.CustomResource {
    /**
     * Get an existing Pipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PipelineState, opts?: pulumi.CustomResourceOptions): Pipeline {
        return new Pipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'codefresh:index/pipeline:Pipeline';

    /**
     * Returns true if the given object is an instance of Pipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Pipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Pipeline.__pulumiType;
    }

    /**
     * Boolean that specifies if the build logs are publicly accessible. Default: false
     */
    public readonly isPublic!: pulumi.Output<boolean | undefined>;
    /**
     * The display name for the pipeline.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A string with original yaml pipeline.
     * - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
     * - or `originalYamlString = file("/path/to/my/codefresh.yml")`
     */
    public readonly originalYamlString!: pulumi.Output<string | undefined>;
    public /*out*/ readonly projectId!: pulumi.Output<string>;
    /**
     * The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
     */
    public /*out*/ readonly revision!: pulumi.Output<number>;
    /**
     * A collection of `spec` blocks as documented below.
     */
    public readonly spec!: pulumi.Output<outputs.PipelineSpec | undefined>;
    /**
     * A list of tags to mark a project for easy management and access control.
     */
    public readonly tags!: pulumi.Output<string[] | undefined>;

    /**
     * Create a Pipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PipelineArgs | PipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PipelineState | undefined;
            resourceInputs["isPublic"] = state ? state.isPublic : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["originalYamlString"] = state ? state.originalYamlString : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["revision"] = state ? state.revision : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as PipelineArgs | undefined;
            resourceInputs["isPublic"] = args ? args.isPublic : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["originalYamlString"] = args ? args.originalYamlString : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["revision"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Pipeline.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Pipeline resources.
 */
export interface PipelineState {
    /**
     * Boolean that specifies if the build logs are publicly accessible. Default: false
     */
    isPublic?: pulumi.Input<boolean>;
    /**
     * The display name for the pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * A string with original yaml pipeline.
     * - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
     * - or `originalYamlString = file("/path/to/my/codefresh.yml")`
     */
    originalYamlString?: pulumi.Input<string>;
    projectId?: pulumi.Input<string>;
    /**
     * The pipeline's revision. Should be added to the **lifecycle/ignore_changes** or incremented mannually each update.
     */
    revision?: pulumi.Input<number>;
    /**
     * A collection of `spec` blocks as documented below.
     */
    spec?: pulumi.Input<inputs.PipelineSpec>;
    /**
     * A list of tags to mark a project for easy management and access control.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Pipeline resource.
 */
export interface PipelineArgs {
    /**
     * Boolean that specifies if the build logs are publicly accessible. Default: false
     */
    isPublic?: pulumi.Input<boolean>;
    /**
     * The display name for the pipeline.
     */
    name?: pulumi.Input<string>;
    /**
     * A string with original yaml pipeline.
     * - `originalYamlString = "version: \"1.0\"\nsteps:\n  test:\n    image: alpine:latest\n    commands:\n      - echo \"ACC tests\""`
     * - or `originalYamlString = file("/path/to/my/codefresh.yml")`
     */
    originalYamlString?: pulumi.Input<string>;
    /**
     * A collection of `spec` blocks as documented below.
     */
    spec?: pulumi.Input<inputs.PipelineSpec>;
    /**
     * A list of tags to mark a project for easy management and access control.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
