// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # Team resource
 *
 * Team is used as a part of access control and allow to define what teams have access to which clusters and pipelines.
 * See the [documentation](https://codefresh.io/docs/docs/administration/access-control/).
 *
 * ## Example usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as codefresh from "@pulumi/codefresh";
 *
 * const developers = new codefresh.Team("developers", {
 *     users: [
 *         "5efc3cb6355c6647041b6e49",
 *         "59009221c102763beda7cf04",
 *     ],
 * });
 * ```
 */
export class Team extends pulumi.CustomResource {
    /**
     * Get an existing Team resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TeamState, opts?: pulumi.CustomResourceOptions): Team {
        return new Team(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'codefresh:index/team:Team';

    /**
     * Returns true if the given object is an instance of Team.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Team {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Team.__pulumiType;
    }

    /**
     * The relevant Account ID.
     */
    public readonly accountId!: pulumi.Output<string>;
    /**
     * The display name for the team.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A list of tags to mark a team for easy management.
     */
    public readonly tags!: pulumi.Output<string[] | undefined>;
    /**
     * The type of the team. Possible values:
     * - __default__
     * - __admin__
     */
    public readonly type!: pulumi.Output<string | undefined>;
    /**
     * A list of user IDs that should be in the team.
     */
    public readonly users!: pulumi.Output<string[] | undefined>;

    /**
     * Create a Team resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TeamArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TeamArgs | TeamState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TeamState | undefined;
            resourceInputs["accountId"] = state ? state.accountId : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
            resourceInputs["users"] = state ? state.users : undefined;
        } else {
            const args = argsOrState as TeamArgs | undefined;
            resourceInputs["accountId"] = args ? args.accountId : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["users"] = args ? args.users : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Team.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Team resources.
 */
export interface TeamState {
    /**
     * The relevant Account ID.
     */
    accountId?: pulumi.Input<string>;
    /**
     * The display name for the team.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of tags to mark a team for easy management.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The type of the team. Possible values:
     * - __default__
     * - __admin__
     */
    type?: pulumi.Input<string>;
    /**
     * A list of user IDs that should be in the team.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Team resource.
 */
export interface TeamArgs {
    /**
     * The relevant Account ID.
     */
    accountId?: pulumi.Input<string>;
    /**
     * The display name for the team.
     */
    name?: pulumi.Input<string>;
    /**
     * A list of tags to mark a team for easy management.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The type of the team. Possible values:
     * - __default__
     * - __admin__
     */
    type?: pulumi.Input<string>;
    /**
     * A list of user IDs that should be in the team.
     */
    users?: pulumi.Input<pulumi.Input<string>[]>;
}
